version: '3.8'

services:
  postgresdb:
    image: postgres:13.4-alpine
    container_name: postgre
    environment:
      POSTGRES_DB: certfinal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"